switcher: 1             # 0 - режим по умолчанию, значения конфигурационного файла игнорируются; 1 - чтение из конфигурации
mode: 2                 # 0 - чистка файлов по имени; 1 - чистка по содержимому; 2 - полное совпадение (имя + содержимое)
log: 1                  # 0 - лог-файл выключен; 1 - лог-файл включен
root: "testDirectory/"   # корневой каталог